spring:
  mvc:
    view:
      prefix: /WEB-INF/vistas/
      suffix: .jsp
  http:
    servlet:
      enable: true
      force: true
      charset: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:mysql://${DB_HOST}:3306/${DB_SCHEMA}?useSSL=false&serverTimezone=UTC&CharacterEncoding=UTF-8
  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: update
